name: oraclelocal

services:
  oracle-xe:
    image: gvenzl/oracle-xe
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: admin
      APP_USER_PASSWORD: admin 
    volumes:
      - oracledata:/opt/oracle/oradata
      - ./listener.ora:/opt/oracle/product/21c/dbhomeXE/network/admin/listener.ora

volumes:
  oracledata:
    driver: local

